### PR TITLE
added a contact page

### PR DESCRIPTION
**Pull request by SnubbullTrouble**
Added a contact page and links to the github and maconcode.com. I did not include the discord because the group should decide if we want an open invite.

### CODE REVIEW

**Comment by ProfBobAllen** [comment]
@SnubbullTrouble does the email you used work?

**Review by ProfBobAllen — CHANGES_REQUESTED** [review]
LOVE the Contact page....
except.... is hello@maconcode.com a valid email address for us?

**Comment by SnubbullTrouble** [comment]
> LOVE the Contact page.... except.... is [hello@maconcode.com](mailto:hello@maconcode.com) a valid email address for us?

Yes, a team member double checked it.

**Comment by azebell** [comment]
Verified contact email is a working forwarding address.

**Review by azebell — APPROVED** [review]

**Review by ProfBobAllen — APPROVED** [review]
I will never doubt you again

**Pull request merged**
